CONCEPTS = {
    "SUBJECT_VERB_AGREEMENT": "Hòa hợp chủ ngữ và động từ",
    "TENSE": "Thì của động từ",
    "VERB_FORM": "Dạng động từ",
    "ARTICLE": "Mạo từ a / an / the",
    "PREPOSITION": "Giới từ",
    "COUNTABLE_UNCOUNTABLE": "Danh từ đếm được và không đếm được",
    "SINGULAR_PLURAL": "Danh từ số ít và số nhiều",
    "PRONOUN": "Đại từ",
    "RELATIVE_CLAUSE": "Mệnh đề quan hệ",
    "CONDITIONAL": "Câu điều kiện",
    "PASSIVE_VOICE": "Câu bị động",
    "MODAL_VERB": "Động từ khuyết thiếu",
    "GERUND_INFINITIVE": "V-ing và to + động từ",
    "WORD_ORDER": "Trật tự từ",
    "COMPARATIVE": "So sánh hơn",
    "SUPERLATIVE": "So sánh nhất",
    "SENTENCE_FRAGMENT": "Câu chưa hoàn chỉnh",
    "RUN_ON_SENTENCE": "Nối câu chưa đúng",
    "CLAUSE_STRUCTURE": "Cấu trúc mệnh đề",
    "CONJUNCTION": "Liên từ",
    "PUNCTUATION": "Dấu câu",
    "DETERMINER": "Từ hạn định",
    "AGREEMENT": "Sự hòa hợp",
    "COMPLEX_SENTENCE_FORMATION": "Tạo câu phức",
    "ARTICLE_A_AN": "Dùng a / an",
    "ARTICLE_THE": "Dùng the",
    "ARTICLE_ZERO": "Không dùng mạo từ",
    "PREPOSITION_INTERESTED_IN": "interested in",
    "PREPOSITION_DEPEND_ON": "depend on",
    "GERUND_ENJOY_DOING": "enjoy + V-ing",
    "INFINITIVE_WANT_TO_DO": "want + to + động từ",
    "AGREE_USAGE": "Dùng động từ agree",
    "ADVANTAGE_COUNTABILITY": "many advantages — danh từ số nhiều",
    "INTERNET_EXPRESSION": "Cụm on the internet",
    "GRAMMAR_USAGE": "Cách dùng ngữ pháp trong ngữ cảnh",
}
ALIASES = {
    "subject_verb": "SUBJECT_VERB_AGREEMENT",
    "sva": "SUBJECT_VERB_AGREEMENT",
    "hòa hợp chủ": "SUBJECT_VERB_AGREEMENT",
    "plural": "SINGULAR_PLURAL",
    "số nhiều": "SINGULAR_PLURAL",
    "countab": "COUNTABLE_UNCOUNTABLE",
    "article": "ARTICLE",
    "mạo từ": "ARTICLE",
    "preposition": "PREPOSITION",
    "giới từ": "PREPOSITION",
    "tense": "TENSE",
    "thì động": "TENSE",
    "verb_form": "VERB_FORM",
    "dạng động": "VERB_FORM",
    "fragment": "SENTENCE_FRAGMENT",
    "run_on": "RUN_ON_SENTENCE",
    "word_order": "WORD_ORDER",
    "relative": "RELATIVE_CLAUSE",
    "conditional": "CONDITIONAL",
    "passive": "PASSIVE_VOICE",
    "modal": "MODAL_VERB",
    "gerund": "GERUND_INFINITIVE",
    "infinitive": "GERUND_INFINITIVE",
    "comparative": "COMPARATIVE",
    "superlative": "SUPERLATIVE",
    "pronoun": "PRONOUN",
    "punctuation": "PUNCTUATION",
    "conjunction": "CONJUNCTION",
    "determiner": "DETERMINER",
    "clause": "CLAUSE_STRUCTURE",
    "agreement": "AGREEMENT",
}
