"""add speaking practice platform"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "008c2258fea3"
down_revision: str | None = "9bdc7dd48184"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speaking_questions",
        sa.Column("part", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=40), nullable=False),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("topic_sets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("situation", sa.Text(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("suggested_ideas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("follow_up_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("difficulty", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("part IN (1, 2, 3)"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_index(op.f("ix_speaking_questions_part"), "speaking_questions", ["part"], unique=False)
    op.create_index(op.f("ix_speaking_questions_topic"), "speaking_questions", ["topic"], unique=False)
    op.create_table(
        "speaking_exam_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_part", sa.Integer(), nullable=False),
        sa.Column("current_sequence", sa.Integer(), nullable=False),
        sa.Column("question_set", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mode IN ('FULL_TEST', 'PART1', 'PART2', 'PART3', 'QUICK_PRACTICE')"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_speaking_exam_sessions_user_id"), "speaking_exam_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "speaking_answers",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("part", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("recording_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audio_path", sa.Text(), nullable=True),
        sa.Column("normalized_audio_path", sa.Text(), nullable=True),
        sa.Column("audio_hash", sa.String(length=64), nullable=True),
        sa.Column("audio_duration_ms", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=80), nullable=True),
        sa.Column("audio_size", sa.Integer(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("transcript_hash", sa.String(length=64), nullable=True),
        sa.Column("transcription_key", sa.String(length=64), nullable=True),
        sa.Column("transcription_model", sa.String(length=100), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audio_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("audio_analysis_key", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["speaking_questions.id"],
        ),
        sa.ForeignKeyConstraint(["session_id"], ["speaking_exam_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence_number"),
    )
    op.create_index(
        op.f("ix_speaking_answers_audio_analysis_key"),
        "speaking_answers",
        ["audio_analysis_key"],
        unique=False,
    )
    op.create_index(op.f("ix_speaking_answers_audio_hash"), "speaking_answers", ["audio_hash"], unique=False)
    op.create_index(op.f("ix_speaking_answers_session_id"), "speaking_answers", ["session_id"], unique=False)
    op.create_index(
        op.f("ix_speaking_answers_transcription_key"), "speaking_answers", ["transcription_key"], unique=False
    )
    op.create_table(
        "speaking_gradings",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("answer_id", sa.String(length=36), nullable=True),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("grammar_score", sa.Float(), nullable=False),
        sa.Column("vocabulary_score", sa.Float(), nullable=False),
        sa.Column("pronunciation_score", sa.Float(), nullable=True),
        sa.Column("fluency_score", sa.Float(), nullable=True),
        sa.Column("structures_score", sa.Float(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("estimated_level", sa.String(length=30), nullable=False),
        sa.Column("summary_vi", sa.Text(), nullable=False),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority_improvements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pronunciation_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fluency_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("structure_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("vocabulary_suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sentence_corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("speaking_frame", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected_transcript", sa.Text(), nullable=False),
        sa.Column("improved_b2_answer", sa.Text(), nullable=False),
        sa.Column("audio_coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_model", sa.String(length=100), nullable=False),
        sa.Column("audio_model", sa.String(length=100), nullable=True),
        sa.Column("transcription_model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("(session_id IS NULL) <> (answer_id IS NULL)"),
        sa.CheckConstraint("fluency_score IS NULL OR (fluency_score >= 0 AND fluency_score <= 10)"),
        sa.CheckConstraint("grammar_score IS NULL OR (grammar_score >= 0 AND grammar_score <= 10)"),
        sa.CheckConstraint("overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 10)"),
        sa.CheckConstraint(
            "pronunciation_score IS NULL OR (pronunciation_score >= 0 AND pronunciation_score <= 10)"
        ),
        sa.CheckConstraint("structures_score IS NULL OR (structures_score >= 0 AND structures_score <= 10)"),
        sa.CheckConstraint("vocabulary_score IS NULL OR (vocabulary_score >= 0 AND vocabulary_score <= 10)"),
        sa.ForeignKeyConstraint(["answer_id"], ["speaking_answers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["speaking_exam_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("answer_id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(op.f("ix_speaking_gradings_cache_key"), "speaking_gradings", ["cache_key"], unique=False)
    op.create_index(op.f("ix_speaking_gradings_user_id"), "speaking_gradings", ["user_id"], unique=False)
    op.create_table(
        "speaking_errors",
        sa.Column("grading_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subtype", sa.String(length=80), nullable=False),
        sa.Column("original", sa.Text(), nullable=False),
        sa.Column("corrected", sa.Text(), nullable=False),
        sa.Column("explanation_vi", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["grading_id"], ["speaking_gradings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_speaking_errors_category"), "speaking_errors", ["category"], unique=False)
    op.create_index(op.f("ix_speaking_errors_grading_id"), "speaking_errors", ["grading_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_speaking_errors_grading_id"), table_name="speaking_errors")
    op.drop_index(op.f("ix_speaking_errors_category"), table_name="speaking_errors")
    op.drop_table("speaking_errors")
    op.drop_index(op.f("ix_speaking_gradings_user_id"), table_name="speaking_gradings")
    op.drop_index(op.f("ix_speaking_gradings_cache_key"), table_name="speaking_gradings")
    op.drop_table("speaking_gradings")
    op.drop_index(op.f("ix_speaking_answers_transcription_key"), table_name="speaking_answers")
    op.drop_index(op.f("ix_speaking_answers_session_id"), table_name="speaking_answers")
    op.drop_index(op.f("ix_speaking_answers_audio_hash"), table_name="speaking_answers")
    op.drop_index(op.f("ix_speaking_answers_audio_analysis_key"), table_name="speaking_answers")
    op.drop_table("speaking_answers")
    op.drop_index(op.f("ix_speaking_exam_sessions_user_id"), table_name="speaking_exam_sessions")
    op.drop_table("speaking_exam_sessions")
    op.drop_index(op.f("ix_speaking_questions_topic"), table_name="speaking_questions")
    op.drop_index(op.f("ix_speaking_questions_part"), table_name="speaking_questions")
    op.drop_table("speaking_questions")
    # ### end Alembic commands ###
