"""add reading question bank and exams"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = '5c96e8660369'
down_revision: Union[str, None] = '008c2258fea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_passages',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('paragraphs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=True),
    sa.Column('vocabulary_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_reading_passages_difficulty'), 'reading_passages', ['difficulty'], unique=False)
    op.create_index(op.f('ix_reading_passages_topic'), 'reading_passages', ['topic'], unique=False)
    op.create_table('reading_exam_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=5), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('passage_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mode IN ('FULL_TEST','PASSAGE_PRACTICE','QUICK_PRACTICE','QUESTION_TYPE_PRACTICE')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_exam_sessions_status'), 'reading_exam_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_reading_exam_sessions_user_id'), 'reading_exam_sessions', ['user_id'], unique=False)
    op.create_table('reading_questions',
    sa.Column('passage_id', sa.String(length=36), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation_vi', sa.Text(), nullable=False),
    sa.Column('option_explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.String(length=5), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("correct_answer IN ('A','B','C','D')"),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_id', 'question_number')
    )
    op.create_index(op.f('ix_reading_questions_passage_id'), 'reading_questions', ['passage_id'], unique=False)
    op.create_index(op.f('ix_reading_questions_question_type'), 'reading_questions', ['question_type'], unique=False)
    op.create_table('reading_answers',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=True),
    sa.Column('is_marked_for_review', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("selected_answer IS NULL OR selected_answer IN ('A','B','C','D')"),
    sa.CheckConstraint('time_spent_seconds >= 0'),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['reading_exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id')
    )
    op.create_index(op.f('ix_reading_answers_session_id'), 'reading_answers', ['session_id'], unique=False)
    op.create_table('reading_results',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('question_type_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passage_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reading_exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_results')
    op.drop_index(op.f('ix_reading_answers_session_id'), table_name='reading_answers')
    op.drop_table('reading_answers')
    op.drop_index(op.f('ix_reading_questions_question_type'), table_name='reading_questions')
    op.drop_index(op.f('ix_reading_questions_passage_id'), table_name='reading_questions')
    op.drop_table('reading_questions')
    op.drop_index(op.f('ix_reading_exam_sessions_user_id'), table_name='reading_exam_sessions')
    op.drop_index(op.f('ix_reading_exam_sessions_status'), table_name='reading_exam_sessions')
    op.drop_table('reading_exam_sessions')
    op.drop_index(op.f('ix_reading_passages_topic'), table_name='reading_passages')
    op.drop_index(op.f('ix_reading_passages_difficulty'), table_name='reading_passages')
    op.drop_table('reading_passages')
    # ### end Alembic commands ###
