"""personalized learning signals coaching and study plans"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "63890193a7ac"
down_revision: str | None = "bcdf7614289e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_attempts",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("analysis_version", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exposure", sa.Integer(), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lexical_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_url", sa.String(length=150), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill", "attempt_id"),
    )
    op.create_index(
        "ix_learning_attempt_user_skill_time",
        "learning_attempts",
        ["user_id", "skill", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "learning_signals",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subcategory", sa.String(length=80), nullable=False),
        sa.Column("concept_key", sa.String(length=100), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column("corrected_text", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("grader_version", sa.String(length=80), nullable=False),
        sa.Column("analysis_version", sa.String(length=30), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill", "attempt_id", "source_version", "fingerprint"),
    )
    op.create_index(
        "ix_learning_signal_user_concept_time",
        "learning_signals",
        ["user_id", "concept_key", "active", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_learning_signal_user_skill_attempt",
        "learning_signals",
        ["user_id", "skill", "attempt_id"],
        unique=False,
    )
    op.create_table(
        "study_plans",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("daily_minutes", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_study_plans_user_id"), "study_plans", ["user_id"], unique=False)
    op.create_table(
        "user_learning_events",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("concept_key", sa.String(length=100), nullable=False),
        sa.Column("source_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("source_exercise_id", sa.String(length=36), nullable=True),
        sa.Column("dedup_key", sa.String(length=160), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedup_key"),
    )
    op.create_index(
        "ix_learning_event_user_concept_time",
        "user_learning_events",
        ["user_id", "concept_key", "created_at"],
        unique=False,
    )
    op.create_table(
        "user_learning_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("analysis_version", sa.String(length=30), nullable=False),
        sa.Column("backfill_status", sa.String(length=20), nullable=False),
        sa.Column("backfill_processed", sa.Integer(), nullable=False),
        sa.Column("backfill_error", sa.String(length=80), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_weaknesses",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subcategory", sa.String(length=80), nullable=False),
        sa.Column("concept_key", sa.String(length=100), nullable=False),
        sa.Column("display_name_vi", sa.String(length=250), nullable=False),
        sa.Column("display_name_en", sa.String(length=250), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("affected_attempt_count", sa.Integer(), nullable=False),
        sa.Column("recent_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mastery_status", sa.String(length=20), nullable=False),
        sa.Column("trend", sa.String(length=25), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill", "concept_key"),
    )
    op.create_index(
        "ix_weakness_user_priority", "user_weaknesses", ["user_id", "priority_score"], unique=False
    )
    op.create_table(
        "learning_lessons",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("weakness_id", sa.String(length=36), nullable=False),
        sa.Column("concept_key", sa.String(length=100), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["weakness_id"], ["user_weaknesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "cache_key"),
    )
    op.create_table(
        "personalized_exercises",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("weakness_id", sa.String(length=36), nullable=False),
        sa.Column("concept_key", sa.String(length=100), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("exercise_type", sa.String(length=40), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("client_request_id", sa.String(length=36), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["weakness_id"], ["user_weaknesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "client_request_id"),
    )
    op.create_table(
        "study_plan_items",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("weakness_id", sa.String(length=36), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=False),
        sa.Column("concept_key", sa.String(length=100), nullable=False),
        sa.Column("activity_type", sa.String(length=30), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["study_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["weakness_id"], ["user_weaknesses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_study_item_user_date", "study_plan_items", ["user_id", "date"], unique=False)
    op.create_table(
        "learning_exercise_answers",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["personalized_exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exercise_id", "item_index"),
    )
    op.create_index(
        "ix_learning_answer_user_time", "learning_exercise_answers", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_learning_answer_user_time", table_name="learning_exercise_answers")
    op.drop_table("learning_exercise_answers")
    op.drop_index("ix_study_item_user_date", table_name="study_plan_items")
    op.drop_table("study_plan_items")
    op.drop_table("personalized_exercises")
    op.drop_table("learning_lessons")
    op.drop_index("ix_weakness_user_priority", table_name="user_weaknesses")
    op.drop_table("user_weaknesses")
    op.drop_table("user_learning_profiles")
    op.drop_index("ix_learning_event_user_concept_time", table_name="user_learning_events")
    op.drop_table("user_learning_events")
    op.drop_index(op.f("ix_study_plans_user_id"), table_name="study_plans")
    op.drop_table("study_plans")
    op.drop_index("ix_learning_signal_user_skill_attempt", table_name="learning_signals")
    op.drop_index("ix_learning_signal_user_concept_time", table_name="learning_signals")
    op.drop_table("learning_signals")
    op.drop_index("ix_learning_attempt_user_skill_time", table_name="learning_attempts")
    op.drop_table("learning_attempts")
    # ### end Alembic commands ###
