"""initial_schema"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9bdc7dd48184"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "writing_questions",
        sa.Column("task_type", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=50), nullable=False),
        sa.Column("topic", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.String(length=10), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("minimum_words", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(task_type = 1 AND minimum_words = 120) OR (task_type = 2 AND minimum_words = 250)"
        ),
        sa.CheckConstraint("task_type IN (1, 2)"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_index(
        op.f("ix_writing_questions_task_type"),
        "writing_questions",
        ["task_type"],
        unique=False,
    )
    op.create_index(op.f("ix_writing_questions_topic"), "writing_questions", ["topic"], unique=False)
    op.create_table(
        "ai_usage_logs",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_usage_logs_user_id"), "ai_usage_logs", ["user_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("refresh_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "exam_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mode IN ('FULL_TEST', 'TASK1', 'TASK2')"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exam_sessions_user_id"), "exam_sessions", ["user_id"], unique=False)
    op.create_table(
        "writing_attempts",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("exam_session_id", sa.String(length=36), nullable=False),
        sa.Column("task_type", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["exam_session_id"], ["exam_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["writing_questions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_session_id", "task_type"),
    )
    op.create_index(
        op.f("ix_writing_attempts_exam_session_id"),
        "writing_attempts",
        ["exam_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_writing_attempts_user_id"),
        "writing_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "writing_gradings",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("task_fulfillment_score", sa.Float(), nullable=False),
        sa.Column("organization_score", sa.Float(), nullable=False),
        sa.Column("vocabulary_score", sa.Float(), nullable=False),
        sa.Column("grammar_score", sa.Float(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("summary_vi", sa.Text(), nullable=False),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "priority_improvements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "structure_feedback",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "task_fulfillment_feedback",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "vocabulary_suggestions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("sentence_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected_version", sa.Text(), nullable=False),
        sa.Column("improved_b2_version", sa.Text(), nullable=False),
        sa.Column("ai_model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("grammar_score >= 0 AND grammar_score <= 10"),
        sa.CheckConstraint("organization_score >= 0 AND organization_score <= 10"),
        sa.CheckConstraint("overall_score >= 0 AND overall_score <= 10"),
        sa.CheckConstraint("task_fulfillment_score >= 0 AND task_fulfillment_score <= 10"),
        sa.CheckConstraint("vocabulary_score >= 0 AND vocabulary_score <= 10"),
        sa.ForeignKeyConstraint(["attempt_id"], ["writing_attempts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_index(
        op.f("ix_writing_gradings_cache_key"),
        "writing_gradings",
        ["cache_key"],
        unique=False,
    )
    op.create_table(
        "writing_errors",
        sa.Column("grading_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("subtype", sa.String(length=80), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("explanation_vi", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["grading_id"], ["writing_gradings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_writing_errors_category"), "writing_errors", ["category"], unique=False)
    op.create_index(
        op.f("ix_writing_errors_grading_id"),
        "writing_errors",
        ["grading_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_writing_errors_grading_id"), table_name="writing_errors")
    op.drop_index(op.f("ix_writing_errors_category"), table_name="writing_errors")
    op.drop_table("writing_errors")
    op.drop_index(op.f("ix_writing_gradings_cache_key"), table_name="writing_gradings")
    op.drop_table("writing_gradings")
    op.drop_index(op.f("ix_writing_attempts_user_id"), table_name="writing_attempts")
    op.drop_index(op.f("ix_writing_attempts_exam_session_id"), table_name="writing_attempts")
    op.drop_table("writing_attempts")
    op.drop_index(op.f("ix_exam_sessions_user_id"), table_name="exam_sessions")
    op.drop_table("exam_sessions")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_ai_usage_logs_user_id"), table_name="ai_usage_logs")
    op.drop_table("ai_usage_logs")
    op.drop_index(op.f("ix_writing_questions_topic"), table_name="writing_questions")
    op.drop_index(op.f("ix_writing_questions_task_type"), table_name="writing_questions")
    op.drop_table("writing_questions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
