export const modes = {
  FULL_TEST: "Thi thử Writing",
  TASK1: "Luyện Task 1",
  TASK2: "Luyện Task 2",
};
export const criteria: Record<string, string> = {
  task_fulfillment: "Đáp ứng yêu cầu",
  organization: "Bố cục & liên kết",
  vocabulary: "Từ vựng",
  grammar: "Ngữ pháp",
};
export const topics: Record<string, string> = {
  education: "Giáo dục",
  technology: "Công nghệ",
  environment: "Môi trường",
  work: "Công việc",
  health: "Sức khỏe",
  transport: "Giao thông",
  family: "Gia đình",
  social_media: "Mạng xã hội",
  tourism: "Du lịch",
  culture: "Văn hóa",
  city_life: "Đời sống đô thị",
  crime: "Tội phạm",
  shopping: "Mua sắm",
  sports: "Thể thao",
  young_people: "Người trẻ",
  older_people: "Người cao tuổi",
  migration: "Di cư",
  communication: "Giao tiếp",
};
export const task1Types: Record<string, string> = {
  formal_email: "Thư trang trọng",
  informal_email: "Thư thân mật",
  request: "Thư đề nghị",
  complaint: "Thư khiếu nại",
  apology: "Thư xin lỗi",
  invitation: "Thư mời",
  giving_information: "Cung cấp thông tin",
  asking_for_information: "Hỏi thông tin",
  thank_you_letter: "Thư cảm ơn",
  giving_advice: "Đưa lời khuyên",
};
export const task2Types: Record<string, string> = {
  opinion: "Nêu quan điểm",
  agree_disagree: "Đồng ý / Không đồng ý",
  discussion: "Thảo luận hai quan điểm",
  advantages_disadvantages: "Ưu điểm / Nhược điểm",
  problems_solutions: "Vấn đề / Giải pháp",
  causes_solutions: "Nguyên nhân / Giải pháp",
  causes_effects: "Nguyên nhân / Hệ quả",
  two_part_question: "Câu hỏi hai phần",
};
export const categories: Record<string, string> = {
  grammar: "Ngữ pháp",
  vocabulary: "Từ vựng",
  spelling: "Chính tả",
  punctuation: "Dấu câu",
  collocation: "Kết hợp từ",
  word_choice: "Lựa chọn từ",
  sentence_structure: "Cấu trúc câu",
  cohesion: "Liên kết ý",
  task_response: "Đáp ứng đề bài",
  register: "Văn phong",
};
export const errorTypes: Record<string, string> = {
  verb_tense: "Thì của động từ",
  tense: "Thì của động từ",
  subject_verb_agreement: "Hòa hợp chủ ngữ – động từ",
  article: "Mạo từ",
  preposition: "Giới từ",
  plural: "Số nhiều",
  singular: "Số ít",
  countable: "Danh từ đếm được",
  uncountable: "Danh từ không đếm được",
  pronoun: "Đại từ",
  relative_clause: "Mệnh đề quan hệ",
  conjunction: "Liên từ",
  conditional: "Câu điều kiện",
  sentence_fragment: "Câu chưa hoàn chỉnh",
  run_on_sentence: "Câu ghép thiếu liên kết",
  word_order: "Trật tự từ",
  comparison: "So sánh",
  modal_verb: "Động từ khuyết thiếu",
  passive_voice: "Câu bị động",
  complex_sentence: "Câu phức",
  punctuation: "Dấu câu",
  repetition: "Lặp từ",
  collocation: "Kết hợp từ",
  word_choice: "Lựa chọn từ",
  register: "Văn phong",
  unnatural_expression: "Diễn đạt thiếu tự nhiên",
  direct_translation: "Dịch sát tiếng Việt",
  lexical_range: "Độ đa dạng từ vựng",
};
